### ISSUE TITLE
rhive.connect()  Insufficient privileges to execute ADD

### ISSUE THREAD

**Issue by kris-ma** [nexr/RHive#102]
2016-10-27 00:33:33,564 WARN org.apache.hive.service.cli.thrift.ThriftCLIService: Error executing statement: 
org.apache.hive.service.cli.HiveSQLException: Insufficient privileges to execute ADD
        at org.apache.hive.service.cli.operation.ExecuteStatementOperation.newExecuteStatementOperation(ExecuteStatementOperation.java:53)
        at org.apache.hive.service.cli.operation.OperationManager.newExecuteStatementOperation(OperationManager.java:122)
        at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:382)
        at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementAsync(HiveSessionImpl.java:373)
        at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:271)
        at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:486)
        at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1313)
        at org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1298)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Insufficient privileges to execute ADD
        at org.apache.hadoop.hive.ql.processors.CommandProcessorFactory.getForHiveCommandInternal(CommandProcessorFactory.java:73)
        at org.apache.hadoop.hive.ql.processors.CommandProcessorFactory.getForHiveCommand(CommandProcessorFactory.java:54)
        at org.apache.hive.service.cli.operation.ExecuteStatementOperation.newExecuteStatementOperation(ExecuteStatementOperation.java:51)
        ... 14 more

**Comment by taeyoung-yoon** [comment]
Hi kris-ma,
Please refer to the [rhive-issue-90](https://github.com/nexr/RHive/issues/90#issuecomment-137461610)
If your problem is solved, please close this issue.
