### ISSUE TITLE
RHive with hiveserver2 + kerberos

### ISSUE THREAD

**Issue by prabhunkl** [nexr/RHive#59]
Hi There,

Is the RHive will work with hiveserver2 which is enabled with kerberos security ?

When I try to connect to Hive I am getting following exception in my R Studio console 

```
rhive.connect(host="hostname.domain.com/default;principal=hive/hostname.domain.com@RELAM.COM",defaultFS="hdfs://namenode.domain.com:8020/user/me",hiveServer2=TRUE)
14/05/05 15:10:52 WARN hdfs.BlockReaderLocal: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
Exception in thread "Thread-35" java.lang.IllegalArgumentException: Kerberos principal should have 3 parts: hive/hostname.domain.com@RELAM.COM:10000/default
        at org.apache.hive.service.auth.KerberosSaslHelper.getKerberosTransport(KerberosSaslHelper.java:64)
        at org.apache.hive.jdbc.HiveConnection.createBinaryTransport(HiveConnection.java:198)
        at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:138)
        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:123)
        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
        at java.sql.DriverManager.getConnection(DriverManager.java:582)
        at java.sql.DriverManager.getConnection(DriverManager.java:185)
        at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:51)
        at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:330)
        at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.run(HiveJdbcClient.java:322)
Error: java.lang.IllegalStateException: Not connected to hiveserver
```

Thanks,
Prabhu.

**Comment by bharatiyengar** [comment]
Hi Prabhunkl,

Can you please share the code for Rhive using Kerberos? I need it badly. Thanks in advance.

**Comment by ranjanarajendran** [comment]
Hi,

Is there a timeline when kerberos for RHive will be available ?  Which version of RHive should we expect this ?

**Comment by samoth21** [comment]
Hi ssshow16:
I think I have some problem connecting R and Hive too, hiveserver2 is not started no matter how I tried. I've posted my problem on stackoverflow and please take a look: 

http://stackoverflow.com/questions/30995208/rhive-hiveserver2-kerberos-keytab-and-principal

I think the both Kerberos keytab and principal need to be adjusted.

**Comment by ranjanarajendran** [comment]
I tried this on a non-kerberized cluster and this is how I did this:

R
library(RHive)
rhive.init(hiveHome="/opt/hive", hiveLib="/opt/hive/lib:/rhive/lib/2.0-0.2", hadoopHome="/opt/hadoop", hadoopConf="/etc/hadoop", hadoopLib="/opt/hadoop/lib", verbose=FALSE)
rhive.connect("hiveserver-ranjana-ci-1940.test.altiscale.com",10000)
OR
rhive.connect("hiveserver-ranjana-ci-1940.test.altiscale.com",hiveServer2=TRUE,updateJar=FALSE,defaultFS="hdfs://nn-host-name:/user/root",user=NULL,password=NULL)
rhive.query("show databases")
rhive.query("use default")
rhive.query("show tables")
rhive.hdfs.ls(path="/user/root")

**Comment by AlexandreLINTE** [comment]
Hello,

Any update on kerberos implementation on RHive ?

Regards,
