### ISSUE TITLE
Error: java.lang.IllegalStateException: Not connected to hiveserver

### ISSUE THREAD

**Issue by jodictionary** [nexr/RHive#78]
Not sure what I should do about this 

<pre>
Exception in thread "Thread-4" java.lang.RuntimeException: java.sql.SQLException: java.lang.ClassNotFoundException
    at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:337)
    at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.run(HiveJdbcClient.java:322)
Caused by: java.sql.SQLException: java.lang.ClassNotFoundException
    at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:41)
    at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:330)
    ... 1 more
Caused by: java.lang.ClassNotFoundException
    at RJavaClassLoader.findClass(RJavaClassLoader.java:383)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:171)
    at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:38)
    ... 2 more
Error: java.lang.IllegalStateException: Not connected to hiveserver
</pre>

**Comment by arun2324** [comment]
Hi,

I am getting similar error as above, I have complied RHive from Github repository. Please advise. I am using the below commands:
> Sys.setenv(HIVE_HOME="/usr/local/lib/apache-hive-2.0.0-bin")
> Sys.setenv(HADOOP_HOME="/usr/local/lib/hadoop-2.7.0")
> library(RHive)
Loading required package: rJava
Loading required package: Rserve
> rhive.env()
        hadoop home: /usr/local/lib/hadoop-2.7.0
        hadoop conf: /usr/local/lib/hadoop-2.7.0/conf
        hive home: /usr/local/lib/apache-hive-2.0.0-bin>
> rhive.connect(hiveServer2=FALSE)Exception in thread "Thread-6" java.lang.RuntimeException: java.sql.SQLException: java.lang.ClassNotFoundException
        at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:332)
        at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.run(HiveJdbcClient.java:314)
Caused by: java.sql.SQLException: java.lang.ClassNotFoundException
        at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:41)
        at com.nexr.rhive.hive.HiveJdbcClient$HiveJdbcConnector.connect(HiveJdbcClient.java:325)
        ... 1 more
Caused by: java.lang.ClassNotFoundException
        at RJavaClassLoader.findClass(RJavaClassLoader.java:383)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.nexr.rhive.hive.DatabaseConnection.connect(DatabaseConnection.java:38)
        ... 2 more
Error: java.lang.IllegalStateException: Not connected to hiveserver
